### ISSUE TITLE
Add ability to customize the end path of the component

### ISSUE THREAD

**Issue by lucasbento** [theshukran/theshukran-react-utils#1]
When I hit `Extract component to a new file` it asks for the name of the component and automatically creates a file under the given path (default `/src/components`) a folder with the name of the component and a file named `index.js` inside of it.

My structure is different, I have a folder inside of `screens` for each feature and a common folder of presentational components, I would love to use this plugin with a way to fit my case.

**Comment by dmainas** [comment]
If I am getting this correctly, you'd like to choose the destination path for every "extraction"? 
If not, could you please post a screenshot or an example of your file hierarchy?

**Comment by lucasbento** [comment]
@dmainas: sorry for the late response and thank you for replying back.

Not each extraction, I would like a config file to set up where all the extracted components would be at.

My structure is

```
├── /screens/
│   ├── /feature1/
│   ├── /feature2/
│   ├── /feature3/
```

**Comment by dmainas** [comment]
@lucasbento You should already be able to do that by setting "/screens/" as the extraction folder path in the vscode preferences (theshukran-react-utils.path is the settings key)

**Comment by lucasbento** [comment]
Oh, thank you, @dmainas!

Sorry for the issue then!
